apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  general:
    logging:
      componentLevels: 
          secret: info
          config: info
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  gateways:
    additionalEgress:
      egress-mx:
        enabled: true
        namespace: egress-mx
      egress-es:
        enabled: true
        namespace: egress-es
    egress:
      enabled: true
      runtime:
        deployment:
          replicas: 1
      service: {}
    enabled: true
    ingress:
      enabled: true
      runtime:
        deployment:
          replicas: 1
      service: {}
    openshiftRoute:
      enabled: false
  policy:
    type: Istiod
  profiles:
  - default
  runtime:
    components:
      pilot:
        deployment:
          replicas: 1
  telemetry:
    type: Istiod
  tracing:
    sampling: 10000
    type: Jaeger