apiVersion: v1
data:
  nginx.conf: |
    events {
    }

    http {
      log_format main '$remote_addr - $remote_user [$time_local]  $status '
      '"$request" $body_bytes_sent "$http_referer" '
      '"$http_user_agent" "$http_x_forwarded_for"';
      access_log /var/log/nginx/access.log main;
      error_log  /var/log/nginx/error.log;

      server {
        listen 443 ssl;

        root /usr/share/nginx/html;
        index index.html;

        server_name *.svc.cluster.local;
        ssl_certificate /etc/nginx-server-certs/tls.crt;
        ssl_certificate_key /etc/nginx-server-certs/tls.key;
        ssl_client_certificate /etc/nginx-ca-certs/example.com.crt;
        ssl_verify_client on;
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2024-03-05T16:29:12Z"
  name: nginx-configmap
  namespace: user1-mesh-external
  resourceVersion: "87653"
  uid: 468fa628-7984-410e-8030-2b1a12766b1a
