apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  namespace: user2-mesh-external
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    run: my-nginx
  sessionAffinity: None
  type: ClusterIP