apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: user1
spec:
  selector:
    istio: egressgateway
  servers:
  - hosts:
    - my-nginx.user1-mesh-external.svc.cluster.local
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: ISTIO_MUTUAL
