apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: egress-mx
  namespace: user1
spec:
  selector:
    app: egress-mx
  servers:
  - hosts:
    - my-nginx-mx.user1-mesh-external.svc.cluster.local
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: ISTIO_MUTUAL
