apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  namespace: user2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sleep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: sleep
    spec:
      containers:
      - command:
        - /bin/sleep
        - "31536000"
        image: ubi8/ubi-minimal:latest
        imagePullPolicy: IfNotPresent
        name: sleep
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx-client-certs
          name: nginx-client-certs
          readOnly: true
        - mountPath: /etc/nginx-ca-certs
          name: nginx-ca-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nginx-client-certs
        secret:
          defaultMode: 420
          secretName: nginx-client-certs
      - name: nginx-ca-certs
        secret:
          defaultMode: 420
          secretName: nginx-ca-certs